# Machine Learning Zoomcamp 2025
# Homework 1: Introduction to Machine Learning

In [4]:
import numpy as np
import pandas as pd

## Q1. Pandas version

In [5]:
np.__version__

'2.3.3'

In [6]:
pd.__version__

'2.3.2'

## Getting the data

In [7]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [9]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


## Q2. Records count

In [8]:
df.shape

(9704, 11)

In [13]:
len(df)

9704

## Q3. Fuel types

In [12]:
pd.unique(df['fuel_type'])

array(['Gasoline', 'Diesel'], dtype=object)

In [15]:
len(pd.unique(df['fuel_type']))

2

## Q4. Missing values

In [20]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [21]:
(df.isnull().sum()!=0).sum()

np.int64(4)

## Q5. Max fuel efficiency

In [40]:
efficiency_asia = df['fuel_efficiency_mpg'][df['origin']=='Asia']

In [53]:
efficiency_asia.max()

23.759122836520497

## Q6. Median value of horsepower

In [59]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [54]:
df['horsepower'].median()

149.0

In [74]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [62]:
df['horsepower'].isna().sum()

np.int64(708)

In [69]:
df['horsepower'].fillna(value=df['horsepower'].mode()[0], inplace=True)

In [70]:
df['horsepower'].isna().sum()

np.int64(0)

In [75]:
df['horsepower'].median()

152.0

## Q7. Sum of weights

In [76]:
filtered_df = df[df['origin']=='Asia']

In [77]:
filtered_df = filtered_df[['vehicle_weight','model_year']]

In [79]:
filtered_df = filtered_df.head(7)

In [83]:
x = filtered_df.to_numpy()

In [85]:
xTx = x.T @ x

In [86]:
xTx

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [87]:
xTx_inverse = np.linalg.inv(xTx)

In [88]:
xTx_inverse

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [89]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [90]:
w = xTx_inverse @ x.T @ y

In [91]:
w

array([0.01386421, 0.5049067 ])

In [92]:
w.sum()

np.float64(0.5187709081074002)